### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [CortneyFitzgerald/TeaCozy#4]
Grade: Meets Expectations

Awesome job on this project! Your code includes all the necessary elements and is easy to read due to your consistent formatting and alignment. You have a great handle on CSS and how to keep things simple as well.

Moving forward, don't be afraid to apply more classes to your elements. It makes it easier to interpret the stylings and see how selectors are applied. Also, start using ids as well as classes. You can read about how to use both here: https://css-tricks.com/the-difference-between-id-and-class/. Adding comments to your code is also helpful, as it provides clarity on the purpose of each block of elements. Finally, on the CSS side of things, there are a lot of resources for making the app for interesting visually. You can do that by using Google Fonts to find cool fonts, and Coolors.co to generate free color palettes to implement in your design. You might find those fun to play with. Again, great job and congratulations!

**Comment by CortneyFitzgerald** [comment]
Thank you! I will use more classes, ids, and comments. Thanks again for the feedback!
